environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --ignore-scripts
  - npm rebuild

test_script:
  - node --version
  - npm --version
  - npm t

build: off
